name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      env:
        TOKEN: ${{secrets.DEPLOYMENT_TOKEN}}
      run: mvn deploy --file pom.xml -Drepository=https://maven.pkg.github.com/mikhasd -Dtoken=$TOKEN
